name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Renovate
        uses: renovatebot/github-action@v37.66.0
        with:
          configurationFile: renovate.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}