name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@latest
        with:
          configurationFile: renovate.json
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}