name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v38.10.0
        with:
          configurationFile: renovate.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}